import { Router } from 'express';
import { login, register, me } from '../controllers/authController.js';
import * as c from '../controllers/dataController.js';
import { protect, adminOnly } from '../middleware/auth.js';
const router = Router();
router.post('/auth/login', login);
router.post('/auth/register', register);
router.get('/auth/me', protect, me);
router.get('/students', protect, adminOnly, c.listStudents);
router.get('/students/:id', protect, c.getStudent);
router.post('/students', protect, adminOnly, c.addStudent);
router.delete('/students/:id', protect, adminOnly, c.deleteStudent);
router.get('/labs', protect, c.listLabs);
router.get('/labs/:id', protect, c.getLab);
router.post('/labs', protect, adminOnly, c.createLab);
router.put('/labs/:id', protect, adminOnly, c.updateLab);
router.delete('/labs/:id', protect, adminOnly, c.deleteLab);
router.get('/attendance/student/:studentId', protect, c.attendanceStudent);
router.get('/attendance/lab/:labId', protect, adminOnly, c.attendanceLab);
router.post('/attendance', protect, adminOnly, c.saveAttendance);
router.put('/attendance/:id', protect, adminOnly, c.updateAttendance);
router.get('/practicals', protect, c.listPracticals);
router.get('/practicals/:id', protect, c.getPractical);
router.post('/practicals', protect, adminOnly, c.createPractical);
router.put('/practicals/:id', protect, adminOnly, c.updatePractical);
router.delete('/practicals/:id', protect, adminOnly, c.deletePractical);
router.get('/progress/student/:studentId', protect, c.studentProgress);
router.post('/progress', protect, c.saveProgress);
router.put('/progress/:id', protect, c.updateProgress);
router.get('/analytics/student/:studentId', protect, c.studentAnalytics);
router.get('/analytics/overview', protect, adminOnly, c.overview);
export default router;
